# Generated by Django 6.0.3 on 2026-03-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('prof_photo', models.ImageField(upload_to='doctors_photos/')),
                ('exp', models.IntegerField(default=0)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
