# Generated by Django 6.0.3 on 2026-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='temp123', max_length=20),
            preserve_default=False,
        ),
    ]
