# Generated by Django 6.0.3 on 2026-03-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='qualification',
        ),
    ]
